INSERT INTO user
	(id, email, password)
	VALUES(1, 'thiago.portocs@gmail.com', '$2a$10$KOXfU5XyGEVajvDuSSM1MOXsLzhnEKujuRGBHzT8akm88Cacl3NJa');

INSERT INTO Category (id, name) VALUES
	(1, 'Business'),
	(2, 'Entertainment'),
	(3, 'General'),
	(4, 'Health'),
	(5, 'Science'),
	(6, 'Sports'),
	(7, 'Technology');

INSERT INTO country (id, name, initials) VALUES
	(1, 'Brazil', 'br'),
	(2, 'United States', 'us'),
	(3, 'United Arab Emirates', 'ae'),
	(4, 'Argentina', 'ar'),
	(5, 'Austria', 'at'),
	(6, 'Australia', 'au'),
	(7, 'Belgium', 'be'),
	(8, 'Bulgaria', 'bg'),
	(9, 'Canada', 'ca'),
	(10, 'Switzerland', 'ch'),
	(11, 'China', 'cn'),
	(12, 'Colombia', 'co'),
	(13, 'Cuba', 'cu'),
	(14, 'Czech Republic', 'cz'),
	(15, 'Germany', 'de'),
	(16, 'Egypt', 'eg'),
	(17, 'France', 'fr'),
	(18, 'United Kingdom', 'gb'),
	(19, 'Greece', 'gr'),
	(20, 'Hong Kong', 'hk'),
	(21, 'Hungary', 'hu'),
	(22, 'Indonesia', 'id'),
	(23, 'Ireland', 'ie'),
	(24, 'Israel', 'il'),
	(25, 'India', 'in'),
	(26, 'Italy', 'it'),
	(27, 'Japan', 'jp'),
	(28, 'Korea', 'kr'),
	(29, 'Lithuania', 'lt'),
	(30, 'Latvia', 'lv'),
	(31, 'Morocco', 'ma'),
	(32, 'Mexico', 'mx'),
	(33, 'Malaysia', 'my'),
	(34, 'Nigeria', 'ng'),
	(35, 'Netherlands', 'nl'),
	(36, 'Norway', 'no'),
	(37, 'New Zealand', 'nz'),
	(38, 'Philippines', 'ph'),
	(39, 'Poland', 'pl'),
	(40, 'Portugal', 'pt'),
	(41, 'Romania', 'ro'),
	(42, 'Serbia', 'rs'),
	(43, 'Russian Federation', 'ru'),
	(44, 'Saudi Arabia', 'sa'),
	(45, 'Sweden', 'se'),
	(46, 'Singapore', 'sg'),
	(47, 'Slovenia', 'si'),
	(48, 'Slovakia', 'sk'),
	(49, 'Thailand', 'th'),
	(50, 'Turkey', 'tr'),
	(51, 'Taiwan', 'tw'),
	(52, 'Ukraine', 'ua'),
	(53, 'Venezuela', 've'),
	(54, 'South Africa', 'za');
  